name: Deploy Website

on:
  push:
    branches:
      - main  # Runs this workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu virtual machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out your GitHub repository

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Deploys the root directory (where your HTML files are)
